### ISSUE TITLE
Set object does not support indexing

### ISSUE THREAD

**Issue by sxiii** [yuxir/steemit_backup#1]
Greetings! Tried your python source (also note that I had to `pip3 install slugify`), but it doesen't work:
```
Traceback (most recent call last):
  File "steemit_backup.py", line 38, in backup
    _category = p['tags'][0]
TypeError: 'set' object does not support indexing
```
Any help would be great @yuxir

**Comment by yuxir** [comment]
This is due to the Steemit API change, change 
  _category = p['tags'][0]
to:
  _category = p['category']

should fix it.

**Comment by yuxir** [comment]
do a git pull to see the latest changes.
